### ISSUE TITLE
HTTPError: 401

### ISSUE THREAD

**Issue by thomasXwang** [vivaxy/alfred-ticktick#1]
Hi, 
I'm encountering this issue in alfred while using your workflow:

````
HTTPError: Response code 401 ()
    at Request.<anonymous> (file:///opt/homebrew/lib/node_modules/alfred-ticktick/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Request._onResponseBase (file:///opt/homebrew/lib/node_modules/alfred-ticktick/node_modules/got/dist/source/core/index.js:727:22)
    at async Request._onResponse (file:///opt/homebrew/lib/node_modules/alfred-ticktick/node_modules/got/dist/source/core/index.js:766:13)
```

-
TickTick(Dida365) 1.3.0
Alfred 5.1.1
darwin 20.6.0
````

Would you know how to fix this error?
Thanks!

**Comment by vivaxy** [comment]
@thomasXwang Hi!
Please check if you have login in by typing `tt login ${YOUR_USER_NAME} ${YOUR_PASSWORD}`.

**Comment by thomasXwang** [comment]
Hi @vivaxy , I tried that, but I got a new error in the small notification popup window:
`HTTPError: Response code 500 ()...`

**Comment by thomasXwang** [comment]
> @thomasXwang Hi! Please check if you have login in by typing `tt login ${YOUR_USER_NAME} ${YOUR_PASSWORD}`.

Hi @vivaxy , when trying this login command, I get a new error in the small notification popup window:
`HTTPError: Response code 500 ()...`
